<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use App\Models\ProductVariant;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0');
        Product::truncate();
        ProductVariant::truncate();
        DB::table('product_variant_attributes')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1');

        $cats = Category::where('type', 'product')->pluck('id', 'slug');

        // ── Helper: ảnh grocery từ Ekomart assets ──
        $g  = fn(int $n) => 'assets/images/grocery/' . str_pad($n, 2, '0', STR_PAD_LEFT) . '.jpg';
        $sh = fn(int $n) => 'assets/images/shop/' . str_pad($n, 2, '0', STR_PAD_LEFT) . '.png';

        $products = [
            // ── Rau củ quả ──────────────────────────────────────────────
            [
                'name'              => 'Nestle Cerelac Mixed Fruits & Wheat with Milk',
                'slug'              => 'nestle-cerelac-mixed-fruits-wheat-milk',
                'short_description' => 'Nutritious baby cereal with mixed fruits, wheat and milk. 500g pack.',
                'description'       => '<p>Nestle Cerelac is a nutritious complementary food for babies from 6 months. Made with whole grain wheat, real fruits and fortified with 18 nutrients including Iron and Zinc.</p><ul><li>500g Pack</li><li>Rich in Iron & Zinc</li><li>No artificial colors or flavors</li></ul>',
                'price'             => 36000,
                'compare_price'     => 48000,
                'sku'               => 'GRO-001',
                'stock'             => 120,
                'stock_status'      => 'in_stock',
                'status'            => 'active',
                'is_featured'       => true,
                'image'             => 'assets/images/grocery/01.jpg',
                'images'            => ['assets/images/grocery/01.jpg', 'assets/images/grocery/02.jpg'],
                'category_slug'     => 'banh-ngu-coc',
                'variants'          => [
                    ['sku' => 'GRO-001-250', 'price' => 22000, 'compare_price' => 30000, 'stock' => 60, 'label' => '250g'],
                    ['sku' => 'GRO-001-500', 'price' => 36000, 'compare_price' => 48000, 'stock' => 60, 'label' => '500g'],
                ],
            ],
            [
                'name'              => 'Organic Fresh Broccoli',
                'slug'              => 'organic-fresh-broccoli',
                'short_description' => 'Fresh organic broccoli, rich in vitamins C and K. Perfect for salads and stir-fry.',
                'description'       => '<p>Our organic broccoli is grown without pesticides in certified organic farms. Packed with vitamins C, K, and folate. Great for steaming, roasting, or eating raw.</p>',
                'price'             => 28000,
                'compare_price'     => null,
                'sku'               => 'VEG-001',
                'stock'             => 80,
                'stock_status'      => 'in_stock',
                'status'            => 'active',
                'is_featured'       => true,
                'image'             => 'assets/images/grocery/02.jpg',
                'images'            => ['assets/images/grocery/02.jpg'],
                'category_slug'     => 'rau-cu-qua',
                'variants'          => [],
            ],
            [
                'name'              => 'Alpro Organic Flavored Fresh Juice',
                'slug'              => 'alpro-organic-flavored-fresh-juice',
                'short_description' => 'Refreshing organic fruit juice with natural flavors. No added sugar.',
                'description'       => '<p>Alpro Organic Juice is made from 100% organic fruits. No added sugar, no artificial flavors. A healthy choice for the whole family.</p><ul><li>1 Liter bottle</li><li>100% Organic</li><li>No added sugar</li></ul>',
                'price'             => 55000,
                'compare_price'     => 72000,
                'sku'               => 'DRK-001',
                'stock'             => 100,
                'stock_status'      => 'in_stock',
                'status'            => 'active',
                'is_featured'       => true,
                'image'             => 'assets/images/grocery/03.jpg',
                'images'            => ['assets/images/grocery/03.jpg', 'assets/images/grocery/04.jpg'],
                'category_slug'     => 'do-uong',
                'variants'          => [
                    ['sku' => 'DRK-001-500', 'price' => 32000, 'compare_price' => 42000, 'stock' => 50, 'label' => '500ml'],
                    ['sku' => 'DRK-001-1L',  'price' => 55000, 'compare_price' => 72000, 'stock' => 50, 'label' => '1 Liter'],
                ],
            ],
            [
                'name'              => 'Foster Farms Breast Nuggets Shaped Chicken',
                'slug'              => 'foster-farms-breast-nuggets-chicken',
                'short_description' => 'Crispy chicken breast nuggets, made from 100% natural chicken. Ready in minutes.',
                'description'       => '<p>Foster Farms Chicken Nuggets are made from 100% natural white meat chicken breast. No artificial ingredients. Perfect for a quick and delicious meal.</p><ul><li>Pack: 400g</li><li>100% Natural Chicken</li><li>Ready in 15 minutes</li></ul>',
                'price'             => 89000,
                'compare_price'     => 115000,
                'sku'               => 'MEA-001',
                'stock'             => 60,
                'stock_status'      => 'in_stock',
                'status'            => 'active',
                'is_featured'       => true,
                'image'             => 'assets/images/grocery/04.jpg',
                'images'            => ['assets/images/grocery/04.jpg', 'assets/images/shop/cart-1.png'],
                'category_slug'     => 'thit-hai-san',
                'variants'          => [
                    ['sku' => 'MEA-001-400', 'price' => 89000,  'compare_price' => 115000, 'stock' => 30, 'label' => '400g'],
                    ['sku' => 'MEA-001-800', 'price' => 165000, 'compare_price' => 210000, 'stock' => 30, 'label' => '800g'],
                ],
            ],
            [
                'name'              => 'Organic Banana Chips Snack',
                'slug'              => 'organic-banana-chips-snack',
                'short_description' => 'Crunchy organic banana chips, lightly salted. Great healthy snack.',
                'description'       => '<p>Made from organically grown bananas, these chips are lightly salted and baked (not fried) for a healthier snack option. Rich in potassium and fiber.</p>',
                'price'             => 42000,
                'compare_price'     => 55000,
                'sku'               => 'SNK-001',
                'stock'             => 150,
                'stock_status'      => 'in_stock',
                'status'            => 'active',
                'is_featured'       => false,
                'image'             => 'assets/images/grocery/05.jpg',
                'images'            => ['assets/images/grocery/05.jpg'],
                'category_slug'     => 'snack-banh-keo',
                'variants'          => [],
            ],
            [
                'name'              => 'Fresh Strawberry 500g Pack',
                'slug'              => 'fresh-strawberry-500g',
                'short_description' => 'Sweet and juicy fresh strawberries, hand-picked daily. Rich in Vitamin C.',
                'description'       => '<p>Our fresh strawberries are hand-picked at peak ripeness for maximum sweetness. Rich in Vitamin C, antioxidants and fiber. Perfect for desserts, smoothies or eating fresh.</p>',
                'price'             => 65000,
                'compare_price'     => 85000,
                'sku'               => 'FRT-001',
                'stock'             => 70,
                'stock_status'      => 'in_stock',
                'status'            => 'active',
                'is_featured'       => true,
                'image'             => 'assets/images/grocery/06.jpg',
                'images'            => ['assets/images/grocery/06.jpg'],
                'category_slug'     => 'trai-cay-tuoi',
                'variants'          => [],
            ],
            [
                'name'              => 'Whole Grain Oats 1kg',
                'slug'              => 'whole-grain-oats-1kg',
                'short_description' => 'Premium whole grain rolled oats. High in fiber, perfect for healthy breakfast.',
                'description'       => '<p>Our whole grain oats are minimally processed to retain maximum nutrition. High in beta-glucan fiber which helps lower cholesterol. Perfect for oatmeal, granola, or baking.</p>',
                'price'             => 95000,
                'compare_price'     => null,
                'sku'               => 'ORG-001',
                'stock'             => 200,
                'stock_status'      => 'in_stock',
                'status'            => 'active',
                'is_featured'       => true,
                'image'             => 'assets/images/grocery/07.jpg',
                'images'            => ['assets/images/grocery/07.jpg'],
                'category_slug'     => 'huu-co-healthy',
                'variants'          => [
                    ['sku' => 'ORG-001-500', 'price' => 52000, 'compare_price' => null,   'stock' => 100, 'label' => '500g'],
                    ['sku' => 'ORG-001-1KG', 'price' => 95000, 'compare_price' => null,   'stock' => 100, 'label' => '1kg'],
                    ['sku' => 'ORG-001-2KG', 'price' => 175000,'compare_price' => 200000, 'stock' => 50,  'label' => '2kg'],
                ],
            ],
            [
                'name'              => 'Premium Basmati Rice 5kg',
                'slug'              => 'premium-basmati-rice-5kg',
                'short_description' => 'Long grain premium Basmati rice, aromatic and fluffy when cooked.',
                'description'       => '<p>Premium aged Basmati rice with long, slender grains that elongate when cooked. Naturally aromatic with a delicate nutty flavor. Ideal for biryanis, pilafs and everyday meals.</p>',
                'price'             => 185000,
                'compare_price'     => 220000,
                'sku'               => 'GRO-002',
                'stock'             => 90,
                'stock_status'      => 'in_stock',
                'status'            => 'active',
                'is_featured'       => false,
                'image'             => 'assets/images/grocery/08.jpg',
                'images'            => ['assets/images/grocery/08.jpg'],
                'category_slug'     => 'banh-ngu-coc',
                'variants'          => [
                    ['sku' => 'GRO-002-2KG', 'price' => 82000,  'compare_price' => 98000,  'stock' => 45, 'label' => '2kg'],
                    ['sku' => 'GRO-002-5KG', 'price' => 185000, 'compare_price' => 220000, 'stock' => 45, 'label' => '5kg'],
                ],
            ],
            [
                'name'              => 'Extra Virgin Olive Oil 500ml',
                'slug'              => 'extra-virgin-olive-oil-500ml',
                'short_description' => 'Cold-pressed extra virgin olive oil from Mediterranean olives. Rich in antioxidants.',
                'description'       => '<p>Our extra virgin olive oil is cold-pressed from hand-picked Mediterranean olives. Rich in monounsaturated fats and antioxidants. Perfect for salad dressings, dipping and light cooking.</p>',
                'price'             => 245000,
                'compare_price'     => 310000,
                'sku'               => 'OIL-001',
                'stock'             => 55,
                'stock_status'      => 'in_stock',
                'status'            => 'active',
                'is_featured'       => true,
                'image'             => 'assets/images/grocery/09.jpg',
                'images'            => ['assets/images/grocery/09.jpg'],
                'category_slug'     => 'gia-vi-dau-an',
                'variants'          => [],
            ],
            [
                'name'              => 'Greek Yogurt Plain 400g',
                'slug'              => 'greek-yogurt-plain-400g',
                'short_description' => 'Thick and creamy Greek yogurt, high in protein. No added sugar.',
                'description'       => '<p>Our Greek yogurt is strained to remove excess whey, resulting in a thick, creamy texture. High in protein and probiotics. No added sugar or artificial flavors.</p>',
                'price'             => 48000,
                'compare_price'     => 62000,
                'sku'               => 'DRY-001',
                'stock'             => 80,
                'stock_status'      => 'in_stock',
                'status'            => 'active',
                'is_featured'       => false,
                'image'             => 'assets/images/grocery/10.jpg',
                'images'            => ['assets/images/grocery/10.jpg'],
                'category_slug'     => 'sua-trung',
                'variants'          => [],
            ],
            [
                'name'              => 'Frozen Mixed Vegetables 1kg',
                'slug'              => 'frozen-mixed-vegetables-1kg',
                'short_description' => 'Convenient frozen mixed vegetables — peas, carrots, corn and beans.',
                'description'       => '<p>Our frozen mixed vegetables are flash-frozen at peak freshness to lock in nutrients. Contains peas, carrots, corn and green beans. No added salt or preservatives.</p>',
                'price'             => 55000,
                'compare_price'     => null,
                'sku'               => 'FRZ-001',
                'stock'             => 120,
                'stock_status'      => 'in_stock',
                'status'            => 'active',
                'is_featured'       => false,
                'image'             => 'assets/images/grocery/11.jpg',
                'images'            => ['assets/images/grocery/11.jpg'],
                'category_slug'     => 'thuc-pham-dong-lanh',
                'variants'          => [],
            ],
            [
                'name'              => 'Organic Chia Seeds 300g',
                'slug'              => 'organic-chia-seeds-300g',
                'short_description' => 'Premium organic chia seeds, rich in Omega-3, fiber and protein.',
                'description'       => '<p>Our organic chia seeds are sourced from certified organic farms. Packed with Omega-3 fatty acids, dietary fiber, protein and calcium. Add to smoothies, yogurt, or make chia pudding.</p>',
                'price'             => 125000,
                'compare_price'     => 160000,
                'sku'               => 'ORG-002',
                'stock'             => 90,
                'stock_status'      => 'in_stock',
                'status'            => 'active',
                'is_featured'       => true,
                'image'             => 'assets/images/grocery/12.jpg',
                'images'            => ['assets/images/grocery/12.jpg'],
                'category_slug'     => 'huu-co-healthy',
                'variants'          => [],
            ],
            [
                'name'              => 'Honey Raw Organic 500g',
                'slug'              => 'honey-raw-organic-500g',
                'short_description' => 'Pure raw organic honey, unfiltered and unheated. Rich in enzymes and antioxidants.',
                'description'       => '<p>Our raw organic honey is harvested from bees that forage on organic wildflowers. Unfiltered and unheated to preserve natural enzymes, pollen and antioxidants. A natural sweetener with health benefits.</p>',
                'price'             => 185000,
                'compare_price'     => 230000,
                'sku'               => 'ORG-003',
                'stock'             => 65,
                'stock_status'      => 'in_stock',
                'status'            => 'active',
                'is_featured'       => true,
                'image'             => 'assets/images/grocery/13.jpg',
                'images'            => ['assets/images/grocery/13.jpg'],
                'category_slug'     => 'gia-vi-dau-an',
                'variants'          => [
                    ['sku' => 'ORG-003-250', 'price' => 98000,  'compare_price' => 125000, 'stock' => 35, 'label' => '250g'],
                    ['sku' => 'ORG-003-500', 'price' => 185000, 'compare_price' => 230000, 'stock' => 30, 'label' => '500g'],
                ],
            ],
            [
                'name'              => 'Avocado Fresh Ripe (2 pcs)',
                'slug'              => 'avocado-fresh-ripe-2pcs',
                'short_description' => 'Creamy ripe avocados, perfect for guacamole, toast or salads.',
                'description'       => '<p>Our avocados are carefully selected at peak ripeness. Creamy texture with a rich, buttery flavor. High in healthy monounsaturated fats, potassium and vitamins K, C, B5 and B6.</p>',
                'price'             => 45000,
                'compare_price'     => 58000,
                'sku'               => 'FRT-002',
                'stock'             => 100,
                'stock_status'      => 'in_stock',
                'status'            => 'active',
                'is_featured'       => true,
                'image'             => 'assets/images/grocery/14.jpg',
                'images'            => ['assets/images/grocery/14.jpg'],
                'category_slug'     => 'trai-cay-tuoi',
                'variants'          => [],
            ],
            [
                'name'              => 'Almond Milk Unsweetened 1L',
                'slug'              => 'almond-milk-unsweetened-1l',
                'short_description' => 'Creamy unsweetened almond milk. Dairy-free, low calorie, fortified with calcium.',
                'description'       => '<p>Our almond milk is made from premium almonds with no added sugar. Fortified with calcium and vitamin D. A great dairy-free alternative for smoothies, cereal and coffee.</p>',
                'price'             => 72000,
                'compare_price'     => 92000,
                'sku'               => 'DRK-002',
                'stock'             => 85,
                'stock_status'      => 'in_stock',
                'status'            => 'active',
                'is_featured'       => false,
                'image'             => 'assets/images/grocery/15.jpg',
                'images'            => ['assets/images/grocery/15.jpg'],
                'category_slug'     => 'do-uong',
                'variants'          => [],
            ],
            [
                'name'              => 'Dark Chocolate 70% Cacao 100g',
                'slug'              => 'dark-chocolate-70-cacao-100g',
                'short_description' => 'Premium dark chocolate with 70% cacao. Rich, intense flavor with health benefits.',
                'description'       => '<p>Our dark chocolate is made from single-origin cacao beans with 70% cacao content. Rich in flavonoids and antioxidants. A guilt-free indulgence that supports heart health.</p>',
                'price'             => 68000,
                'compare_price'     => 85000,
                'sku'               => 'SNK-002',
                'stock'             => 110,
                'stock_status'      => 'in_stock',
                'status'            => 'active',
                'is_featured'       => false,
                'image'             => 'assets/images/grocery/16.jpg',
                'images'            => ['assets/images/grocery/16.jpg'],
                'category_slug'     => 'snack-banh-keo',
                'variants'          => [],
            ],
            [
                'name'              => 'Free Range Eggs 10 pcs',
                'slug'              => 'free-range-eggs-10pcs',
                'short_description' => 'Fresh free-range eggs from hens raised on open pastures. Rich in protein.',
                'description'       => '<p>Our free-range eggs come from hens that roam freely on open pastures. Richer in Omega-3 and vitamins compared to conventional eggs. Perfect for any meal of the day.</p>',
                'price'             => 38000,
                'compare_price'     => null,
                'sku'               => 'DRY-002',
                'stock'             => 200,
                'stock_status'      => 'in_stock',
                'status'            => 'active',
                'is_featured'       => true,
                'image'             => 'assets/images/grocery/17.jpg',
                'images'            => ['assets/images/grocery/17.jpg'],
                'category_slug'     => 'sua-trung',
                'variants'          => [],
            ],
            [
                'name'              => 'Salmon Fillet Fresh 300g',
                'slug'              => 'salmon-fillet-fresh-300g',
                'short_description' => 'Fresh Atlantic salmon fillet, rich in Omega-3. Perfect for grilling or baking.',
                'description'       => '<p>Our fresh Atlantic salmon fillets are sourced from sustainable fisheries. Rich in Omega-3 fatty acids, high-quality protein and B vitamins. Ideal for grilling, baking or pan-searing.</p>',
                'price'             => 195000,
                'compare_price'     => 250000,
                'sku'               => 'SEA-001',
                'stock'             => 45,
                'stock_status'      => 'in_stock',
                'status'            => 'active',
                'is_featured'       => true,
                'image'             => 'assets/images/grocery/18.jpg',
                'images'            => ['assets/images/grocery/18.jpg'],
                'category_slug'     => 'thit-hai-san',
                'variants'          => [],
            ],
            [
                'name'              => 'Quinoa White Organic 500g',
                'slug'              => 'quinoa-white-organic-500g',
                'short_description' => 'Organic white quinoa — complete protein, gluten-free superfood.',
                'description'       => '<p>Quinoa is a complete protein containing all 9 essential amino acids. Our organic white quinoa is gluten-free, high in fiber and minerals. Cook as a rice substitute or add to salads and soups.</p>',
                'price'             => 145000,
                'compare_price'     => 180000,
                'sku'               => 'ORG-004',
                'stock'             => 75,
                'stock_status'      => 'in_stock',
                'status'            => 'active',
                'is_featured'       => false,
                'image'             => 'assets/images/grocery/19.jpg',
                'images'            => ['assets/images/grocery/19.jpg'],
                'category_slug'     => 'huu-co-healthy',
                'variants'          => [],
            ],
            [
                'name'              => 'Coconut Water 330ml Can',
                'slug'              => 'coconut-water-330ml-can',
                'short_description' => 'Pure natural coconut water, no added sugar. Natural electrolytes for hydration.',
                'description'       => '<p>Our coconut water is sourced from young green coconuts. Naturally rich in electrolytes — potassium, magnesium and sodium. No added sugar or preservatives. Perfect post-workout hydration.</p>',
                'price'             => 28000,
                'compare_price'     => 35000,
                'sku'               => 'DRK-003',
                'stock'             => 180,
                'stock_status'      => 'in_stock',
                'status'            => 'active',
                'is_featured'       => false,
                'image'             => 'assets/images/grocery/20.jpg',
                'images'            => ['assets/images/grocery/20.jpg'],
                'category_slug'     => 'do-uong',
                'variants'          => [],
            ],
            [
                'name'              => 'Peanut Butter Crunchy 340g',
                'slug'              => 'peanut-butter-crunchy-340g',
                'short_description' => 'Natural crunchy peanut butter with no added sugar or palm oil.',
                'description'       => '<p>Made from 100% roasted peanuts with no added sugar, salt or palm oil. High in protein and healthy fats. Great on toast, in smoothies or as a dip for fruits and vegetables.</p>',
                'price'             => 82000,
                'compare_price'     => 105000,
                'sku'               => 'GRO-003',
                'stock'             => 95,
                'stock_status'      => 'in_stock',
                'status'            => 'active',
                'is_featured'       => false,
                'image'             => 'assets/images/shop/01.png',
                'images'            => ['assets/images/shop/01.png', 'assets/images/shop/02.png'],
                'category_slug'     => 'banh-ngu-coc',
                'variants'          => [],
            ],
            [
                'name'              => 'Tomato Cherry Organic 250g',
                'slug'              => 'tomato-cherry-organic-250g',
                'short_description' => 'Sweet organic cherry tomatoes, bursting with flavor. Great for salads.',
                'description'       => '<p>Our organic cherry tomatoes are grown in certified organic greenhouses. Sweet, juicy and bursting with lycopene and vitamin C. Perfect for salads, pasta or snacking.</p>',
                'price'             => 32000,
                'compare_price'     => null,
                'sku'               => 'VEG-002',
                'stock'             => 130,
                'stock_status'      => 'in_stock',
                'status'            => 'active',
                'is_featured'       => false,
                'image'             => 'assets/images/shop/03.png',
                'images'            => ['assets/images/shop/03.png'],
                'category_slug'     => 'rau-cu-qua',
                'variants'          => [],
            ],
            [
                'name'              => 'Mango Alphonso Premium 1kg',
                'slug'              => 'mango-alphonso-premium-1kg',
                'short_description' => 'Premium Alphonso mangoes — the king of mangoes. Sweet, aromatic and fiber-rich.',
                'description'       => '<p>Alphonso mangoes are considered the finest variety of mango. Known for their rich, creamy, tender texture and delicate, non-fibrous pulp. Naturally sweet with a distinct aroma.</p>',
                'price'             => 120000,
                'compare_price'     => 150000,
                'sku'               => 'FRT-003',
                'stock'             => 55,
                'stock_status'      => 'in_stock',
                'status'            => 'active',
                'is_featured'       => true,
                'image'             => 'assets/images/shop/04.png',
                'images'            => ['assets/images/shop/04.png'],
                'category_slug'     => 'trai-cay-tuoi',
                'variants'          => [],
            ],
            [
                'name'              => 'Protein Bar Chocolate Fudge 60g',
                'slug'              => 'protein-bar-chocolate-fudge-60g',
                'short_description' => 'High-protein snack bar with 20g protein. Low sugar, great for post-workout.',
                'description'       => '<p>Each bar contains 20g of high-quality whey protein with only 5g of sugar. Made with real chocolate and natural ingredients. Perfect pre or post-workout snack or healthy meal replacement.</p>',
                'price'             => 55000,
                'compare_price'     => 68000,
                'sku'               => 'SNK-003',
                'stock'             => 160,
                'stock_status'      => 'in_stock',
                'status'            => 'active',
                'is_featured'       => false,
                'image'             => 'assets/images/shop/05.png',
                'images'            => ['assets/images/shop/05.png'],
                'category_slug'     => 'snack-banh-keo',
                'variants'          => [],
            ],
            [
                'name'              => 'Cheddar Cheese Block 200g',
                'slug'              => 'cheddar-cheese-block-200g',
                'short_description' => 'Mature cheddar cheese with a sharp, tangy flavor. Perfect for cooking and snacking.',
                'description'       => '<p>Our mature cheddar is aged for a minimum of 12 months to develop its characteristic sharp, tangy flavor. Rich in calcium and protein. Great for sandwiches, burgers, pasta and cheese boards.</p>',
                'price'             => 115000,
                'compare_price'     => 145000,
                'sku'               => 'DRY-003',
                'stock'             => 70,
                'stock_status'      => 'in_stock',
                'status'            => 'active',
                'is_featured'       => false,
                'image'             => 'assets/images/shop/06.png',
                'images'            => ['assets/images/shop/06.png'],
                'category_slug'     => 'sua-trung',
                'variants'          => [],
            ],
            [
                'name'              => 'Frozen Shrimp Peeled 500g',
                'slug'              => 'frozen-shrimp-peeled-500g',
                'short_description' => 'Ready-to-cook frozen peeled shrimp. No preservatives, flash-frozen for freshness.',
                'description'       => '<p>Our frozen shrimp are peeled and deveined for convenience. Flash-frozen immediately after harvest to lock in freshness and flavor. No added preservatives. Ready to cook straight from frozen.</p>',
                'price'             => 145000,
                'compare_price'     => 185000,
                'sku'               => 'FRZ-002',
                'stock'             => 80,
                'stock_status'      => 'in_stock',
                'status'            => 'active',
                'is_featured'       => true,
                'image'             => 'assets/images/shop/07.png',
                'images'            => ['assets/images/shop/07.png'],
                'category_slug'     => 'thuc-pham-dong-lanh',
                'variants'          => [],
            ],
            [
                'name'              => 'Green Tea Matcha Powder 100g',
                'slug'              => 'green-tea-matcha-powder-100g',
                'short_description' => 'Ceremonial grade matcha powder from Japan. Rich in antioxidants and L-theanine.',
                'description'       => '<p>Our ceremonial grade matcha is stone-ground from shade-grown Japanese green tea leaves. Rich in antioxidants, L-theanine and chlorophyll. Use for traditional matcha tea, lattes, smoothies or baking.</p>',
                'price'             => 220000,
                'compare_price'     => 280000,
                'sku'               => 'DRK-004',
                'stock'             => 50,
                'stock_status'      => 'in_stock',
                'status'            => 'active',
                'is_featured'       => true,
                'image'             => 'assets/images/shop/08.png',
                'images'            => ['assets/images/shop/08.png'],
                'category_slug'     => 'do-uong',
                'variants'          => [],
            ],
        ];

        // Get attributes for seeding variants
        $weightAttr = \App\Models\Attribute::where('name', 'Trọng lượng')->first();
        $volumeAttr = \App\Models\Attribute::where('name', 'Dung tích')->first();

        foreach ($products as $data) {
            $catSlug  = $data['category_slug'];
            $variants = $data['variants'] ?? [];
            unset($data['category_slug'], $data['variants']);

            $data['category_id']  = $cats[$catSlug] ?? null;
            $data['has_variants'] = count($variants) > 0;

            $product = Product::create($data);

            foreach ($variants as $i => $v) {
                $variant = ProductVariant::create([
                    'product_id'    => $product->id,
                    'sku'           => $v['sku'],
                    'price'         => $v['price'],
                    'compare_price' => $v['compare_price'] ?? null,
                    'stock'         => $v['stock'],
                    'image'         => $v['image'] ?? null,
                    'is_active'     => true,
                    'sort_order'    => $i,
                ]);

                // Linking attributes if label matches known values
                if (isset($v['label'])) {
                    $attr = null;
                    if (str_contains($v['label'], 'g') || str_contains($v['label'], 'kg')) $attr = $weightAttr;
                    if (str_contains($v['label'], 'l') || str_contains($v['label'], 'ml')) $attr = $volumeAttr;

                    if ($attr) {
                        $val = \App\Models\AttributeValue::where('attribute_id', $attr->id)
                            ->where('value', $v['label'])
                            ->first();
                        if ($val) {
                            DB::table('product_variant_attributes')->insert([
                                'variant_id'         => $variant->id,
                                'attribute_id'       => $attr->id,
                                'attribute_value_id' => $val->id,
                            ]);
                        }
                    }
                }
            }
        }

        $this->command->info('✅ Đã seed ' . Product::count() . ' sản phẩm (' . ProductVariant::count() . ' variants)');
    }
}
